export const COLUMN_PARTICIPANT_ID = 0;
export const COLUMN_PARTICIPANT_NAME = 1;
export const COLUMN_PARTICIPANT_PHONE = 2;
export const COLUMN_PARTICIPANT_EMAIL = 3;
export const COLUMN_PARTICIPANT_REMEDIAL = 4;
export const SNOWFLAKE_GENERATOR_EPOCH = 1672531200;  // Jan 1, 2023, 00:00 UTC
