export const COLUMN_PARTICIPANT_ID = 0;
export const COLUMN_PARTICIPANT_NAME = 1;
export const COLUMN_PARTICIPANT_PHONE = 2;
export const COLUMN_PARTICIPANT_EMAIL = 3;
export const COLUMN_PARTICIPANT_REMEDIAL = 4;
